#!/bin/bash

srcdir=$1

echo "/* Autogenerated file */" > $srcdir/shaders.h
echo "" >> $srcdir/shaders.h
echo "#ifndef SHADERS_H" >> $srcdir/shaders.h
echo "#define SHADERS_H" >> $srcdir/shaders.h
echo "" >> $srcdir/shaders.h

find "$srcdir/shaders" -name '*.bin.h' -exec bash -c 'echo "#include \"'{}'\"" >> '"$srcdir/shaders.h" \;

echo "" >> $srcdir/shaders.h
echo "#endif /* SHADERS_H */" >> $srcdir/shaders.h
