#!/bin/bash

srcdir=$1

cd $srcdir || exit 1

echo "/* Autogenerated file */" > shaders.h
echo "" >> shaders.h
echo "#ifndef SHADERS_H" >> shaders.h
echo "#define SHADERS_H" >> shaders.h
echo "" >> shaders.h

find "shaders" -name '*.bin.h' -exec bash -c 'echo "#include \"'{}'\"" >> '"shaders.h" \;

echo "" >> shaders.h
echo "#endif /* SHADERS_H */" >> shaders.h
